version: 2

defaults: &defaults
  docker:
    - image: circleci/node:12
  working_directory: ~/repo

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Lerna bootstrap
          command: yarn run bootstrap

      - run:
          name: Build packages
          command: yarn run build
      
      - persist_to_workspace:
          root: ~/repo
          paths: .
  
  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Run tests
          command: yarn run test

      - run:
          name: Upload test coverage
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
